# Generated by Django 4.1.5 on 2023-01-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.company",
            ),
        ),
    ]
